---
title: "Responsibility for Not Wanting To Know"
author: "Lara Kirfel, Xenia Bunk, Ro'i Zultan & Tobias Gerstenberg"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  bookdown::html_document2:
    toc: true
    toc_depth: 4
    toc_float: true
    theme: cosmo
    highlight: tango
---

# Load packages
```{r, message=FALSE, warning=FALSE}

library("dplyr")
library("tidyverse")
library("tibble")
library("pwr")
library("car")
library("brms")  
library("knitr")       # for RMarkdown commands 
library("kableExtra")  # for nice tables
```

```{r}
# set ggplot theme 
theme_set(theme_classic())

# set knitr options
opts_chunk$set(comment = "",
               fig.show = "hold")

# suppress summarise() grouping warning 
options(dplyr.summarise.inform = F)
```

# Experiment 1: Manipulating Ignorance
## Read in data 

```{r}
# # Read in demographics data
participants <- read.csv(file="willful_ignorance_study_4-participants.csv") %>% 
  select(-c(proliferate.condition, error))

# # Read in response data
responses <- read.csv(file="willful_ignorance_study_4-responses.csv") %>% 
  select(-c(proliferate.condition, error))

# # Merge datafiles
Data4.df <- merge(responses, participants, by="workerid") 
```


#Demographics

```{r}
Data4_demo.df <-Data4.df%>% 
    summarise(n=n(),
             mean_age = mean(age, na.rm=TRUE),
             std_age=sd(age,na.rm=TRUE),
             female=sum(gender=="Female"),
             male=sum(gender=="Male"),
             non_binary=sum(gender=="Non-binary"),
             asian=sum(race=="Asian"),
             white=sum(race=="White"),
             black=sum(race=="Black/African American"),
             multi=sum(race=="Multiracial"),
             hawai=sum(race=="Native Hawaiian/Pacific Islander"),
             other=sum(race=="other_race")
             )

```
# Edit Data

```{r}
# # New columns with condition information 
Exp4.df <- Data4.df  %>% 
  gather("index", "value", -c(workerid, condition, age, ethnicity, gender, feedback, race))%>% 
  mutate(scenario_order  =
           case_when(
             str_detect(index, "1") ~ "1",
             str_detect(index, "2") ~ "2",
             str_detect(index, "3") ~ "3",
             str_detect(index, "4") ~ "4",
           )) %>% 
mutate(index =
         case_when(
           str_detect(index, "_response_first") ~ "responsibility_rating",
           str_detect(index, "_response_second") ~ "belief_rating",
           str_detect(index, "scenario") ~ "scenario") ## order important, do not change
         ) %>% 
spread(index, value) %>%
mutate(Ignorance =
         case_when(
           str_detect(scenario, "unintentional_") ~ "Unintentional\nIgnorance" ,
           str_detect(scenario, "intentional_") ~ "Willful\nIgnorance" ,
         )) %>% 
mutate(Action_Model =
         case_when(
           str_detect(scenario, "_dependent") ~ "Action Model: Dependent",
           str_detect(scenario, "_independent") ~ "Action Model: Independent",
         )) %>% 
mutate(scenario_type  =
           case_when(
        condition == "condition1" & scenario ==  "unintentional_dependent"~ "fertilizer",
        condition == "condition1" & scenario ==  "unintentional_independent"~ "laundry",
        condition == "condition1" & scenario ==  "intentional_dependent" ~ "paint",     
        condition == "condition1" & scenario ==  "intentional_independent" ~ "sunscreen",
        condition == "condition2" & scenario ==  "unintentional_dependent"~ "paint",
        condition == "condition2" & scenario ==  "unintentional_independent"~ "fertilizer",
        condition == "condition2" & scenario ==  "intentional_dependent" ~ "laundry",     
        condition == "condition2" & scenario ==  "intentional_independent" ~ "paint",
        condition == "condition3" & scenario ==  "intentional_dependent"~ "fertilizer",
        condition == "condition3" & scenario ==  "intentional_independent"~ "laundry",
        condition == "condition3" & scenario ==  "unintentional_dependent" ~ "paint",     
        condition == "condition3" & scenario ==  "unintentional_independent" ~ "sunscreen",
        condition == "condition4" & scenario ==  "intentional_independent"~ "fertilizer",
        condition == "condition4" & scenario ==  "unintentional_dependent"~ "laundry",
        condition == "condition4" & scenario ==  "unintentional_independent" ~ "paint",     
        condition == "condition4" & scenario ==  "intentional_dependent" ~ "sunscreen"
        )) %>% 
    mutate(Ignorance= factor(Ignorance, levels=c("Unintentional\nIgnorance", "Willful\nIgnorance"))) %>% 
    mutate(Action_Model= factor(Action_Model, levels=c("Action Model: Dependent", "Action Model: Independent"))) %>% 
    mutate(scenario= factor(scenario, levels=c("unintentional_dependent", "intentional_dependent", "unintentional_independent", "intentional_independent"))) %>% 
    mutate(responsibility_rating = as.numeric(responsibility_rating)) %>% 
    mutate(belief_rating = as.numeric(belief_rating)) 

```

#Demographics

```{r}

Data1_demo.df <-Data1.df%>% 
    summarise(n=n(),
             mean_age = mean(age),
             std_age=sd(age),
             female=sum(gender=="Female"),
             non_binary=sum(gender=="Non-binary"))

#   print_table()
   
```


```{r}
#### Set Theme
myTheme <-   theme(axis.title.x  = element_blank(), 
                   axis.title.y = element_text(color="black", size = 18, vjust=.9), 
                   axis.text.x = element_text(color="black", size = 16),
                   axis.text.y = element_text(color="black", size = 18), 
                   strip.text.x = element_text(color="black", size = 16),
                   legend.text = element_text(color="black", size = 12),
                   panel.grid.major = element_blank(),
                   panel.grid.minor = element_blank(),
                   strip.background = element_rect(fill="white"),
                   legend.title = element_blank()
)
```

```{r}
Fig3a <- Exp4.df %>% 
  ggplot(aes(x=Ignorance, y=responsibility_rating, group=Ignorance, fill=Ignorance)) +
  coord_cartesian(ylim = c(0,10)) +
  scale_y_continuous(breaks = seq(0, 10, by=1))+
  stat_summary(fun = mean, geom = "bar", colour = "black", alpha=0.7) +
  stat_summary(fun.data = mean_cl_boot, geom = "linerange", width = 1, size=1) +
  geom_jitter(position = position_jitter(height = 0.2, width=0.15), alpha = 
                0.06, colour="black")+
  labs( y="Responsibility Rating")+
  scale_fill_brewer(palette="Paired")+
  guides(fill = FALSE, colour = FALSE)+
  facet_wrap(~Action_Model)+
  theme_bw()+
  myTheme
  #theme(axis.text.x = element_text(angle = 15, hjust = 1, color="black", size = 14))


#Show plot
plot(Fig3a)
ggsave(Fig3a, file="Fig3a.pdf", dpi=400, height = 4, width = 7)
```

```{r}
my_colors <- RColorBrewer::brewer.pal(12, "Paired")[5:6]


Fig3b <- Exp4.df %>% 
  ggplot(aes(x=Ignorance, y=belief_rating, group=Ignorance, fill=Ignorance)) +
  coord_cartesian(ylim = c(0,10)) +
  scale_y_continuous(breaks = seq(0, 10, by=1))+
  stat_summary(fun = mean, geom = "bar", colour = "black", alpha=0.7) +
  stat_summary(fun.data = mean_cl_boot, geom = "linerange", width = 1, size=1) +
  geom_jitter(position = position_jitter(height = 0.2, width=0.15), alpha = 
                0.06, colour="black")+
  labs( y="Belief Rating")+
  scale_fill_manual(values=my_colors)+
  guides(fill = FALSE, colour = FALSE)+
  facet_wrap(~Action_Model)+
  theme_bw()+
  myTheme
  #theme(axis.text.x = element_text(angle = 15, hjust = 1, color="black", size = 14))


#Show plot
plot(Fig3b)
ggsave(Fig3b, file="Fig3b.pdf", dpi=400, height = 4, width = 7)
```
## Combined figures 

```{r, fig.width=8, fig.height=10}
Fig3a + Fig3b + 
  plot_layout(ncol = 1) + 
  plot_annotation(tag_levels = "A") & 
  theme(plot.tag = element_text(face = 'bold', size = 22))

ggsave(file="../../../figures/plots/experiment3.pdf",
       height = 8,
       width = 7)
```

```{r}
##################### Analysis
#### Responsibility Rating

contrasts(Exp4.df$Ignorance) = contr.sum(2)
contrasts(Exp4.df$Action_Model) = contr.sum(2)

#### Responsibility Rating

fit_responsibility_judgment = brm(formula = responsibility_rating ~  1 + Action_Model*Ignorance + (1 | workerid) + (1 | scenario_type),
                             data = Exp4.df,
                             seed = 1,
                             cores = 2)


#### Belief Rating

fit_belief_judgment = brm(formula = belief_rating ~  1 + Action_Model*Ignorance + (1 | workerid) + (1 | scenario_type),
                                  data = Exp4.df,
                                  seed = 1,
                                  cores = 2)

fit_belief_judgment




Exp4b.df <- Exp4.df %>% 
  filter(Action_Model == "Action Model: Independent")


fit_responsibility_judgment2 = brm(formula = responsibility_rating ~  1 + Ignorance + (1 | workerid) + (1 | scenario_type),
                             data = Exp4b.df,
                             seed = 1,
                             cores = 2)

summary(fit_responsibility_judgment2)


```


